baseURL = 'https://debchanda.github.io/hugo-all-tailwind/'
languageCode = 'en-us'
title = 'My New Hugo Site'
publishDir = "docs"

[params]
colorScheme = "avocado"
[params.colors]
colorPrimary    = "rose"
colorSecondary  = "pink"
colorNeutral    = "slate"